### ISSUE TITLE
Get Dataverse button  Functionality

### ISSUE THREAD

**Issue by Devanshu1603** [multiverseweb/Dataverse#100]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

- Get dataverse button is not working

### Expected Behaviour

- on clicking the button an alert must pop about stating that " this feature will be available soon " .

### Screenshot

https://github.com/user-attachments/assets/0d3d1074-a02d-4fe5-9c55-be9cde16f2d9

### Proposed Solution

- on clicking the button an alert must pop about stating that " this feature will be available soon " .

**Comment by Devanshu1603** [comment]
@jency1  @Tejas-Gupta-7  please assign me this issue under gssoc-extended.

**Comment by multiverseweb** [comment]
Hey @Devanshu1603, actually the alert already exists and it pops up when the button is clicked. The problem is that there is an imabe with `opacity: 0; ` over the button due to which the mouse click is not detected. 


https://github.com/user-attachments/assets/00062c2d-49d3-4810-bf30-651dde9a0cd6

You can fix this by simply increasing the margin above the image or the div containing the image.
Good luck!
