### ISSUE TITLE
Improving UI in dark mode

### ISSUE THREAD

**Issue by Riddhi12349** [multiverseweb/Dataverse#119]
Found a bug? Please fill out the sections below. 👍

### Current Behaviour

- Describe what's happening right now. Be as detailed as possible.
Navbar not clearly visible in dark mode

### Expected Behaviour

- Explain what you expected to happen instead.
Navbar should be clearly using white background for navbar buttons instead of grey

### Screenshot

- Attach any relevant screenshots that help illustrate the issue.
![image](https://github.com/user-attachments/assets/eb053539-ab2c-4461-b392-409d92a6e482)

### Proposed Solution

- Suggest how the issue could be fixed or what steps might resolve it.

### Technical Details

- Browser version, screen recording, console logs, network requests.
- Node.js version
- Any other information you think could help in resolving the issue.

**Comment by Riddhi12349** [comment]
Please assign me the issue under gssoc extd

**Comment by multiverseweb** [comment]
Hey @Riddhi12349, you have raised the issue in wrong repository. The issue is about [Codeit](https://github.com/multiverseweb/CodeIt) and you have raised it in [Dataverse](https://github.com/multiverseweb/Dataverse). Comment on [this issue](https://github.com/multiverseweb/CodeIt/issues/66) to get assigned.
